spring:
  application:
    name: gateway

server:
  port: 5050

gateway:
  default-target-base-url: http://190.180.0.111:9099
  routes:
#    - path-prefix: /master-data-hub
#      target-base-url: http://localhost:8088
#    - path-prefix: /cashflow-manager
#      target-base-url: http://localhost:7280
    - path-prefix: /master/financial-security
      target-base-url: http://localhost:8085
    - path-prefix: /master/counterparty/
      target-base-url: http://localhost:8087
